version: '3.8'

services:
#  freeradius:
#    image: freeradius/freeradius-server:latest
#    container_name: freeradius
#    ports:
#      - "1812:1812/udp"
#      - "1813:1813/udp"
#    volumes:
#      - "./configs/radius/users:/etc/raddb/users"
#      - "./configs/radius/clients.conf:/etc/raddb/clients.conf"
#    environment:
#      - DB_HOST=mysql
#      - RAD_DEBUG=yes
#    depends_on:
#      - mysql
#    restart: always
#    networks:
#      - smartcom

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./configs/mysql/master/data:/var/lib/mysql"
      #- "./configs/mysql/master/conf.d:/etc/mysql/conf.d"
      - "./configs/mysql/radius.sql:/docker-entrypoint-initdb.d/radius.sql"    
    environment:
      - MYSQL_ROOT_PASSWORD=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=radpass
      - MYSQL_DATABASE=radius
    restart: always
    networks:
      - smartcom

  app-db:
    image: postgres:latest
    container_name: app-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - smartcom

  routeros:
    image: evilfreelancer/docker-routeros:latest
    container_name: routeros
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm
    ports:
      - "2222:22"
      - "23:23"
      - "81:80"
      - "5900:5900"
      - "8728:8728"
      - "8729:8729"
    networks:
      - smartcom

volumes:
  app-db-data:

networks:
  smartcom:
