-- Add migration script here
--will add audit data for record creation(user_id(created_by),and date of creation(created_by)
--record changes date of change(updated_at) and user_id(update_by)) to the table
--and record deletion date of deletion(deleted_at) and user_id(deleted_by) to the table
--for having deletion i should use soft deletes